#!/usr/bin/env node
/**
 * update_nav.js — Remove "Home" and "Browse" from navigation across all standalone pages
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

// Standalone pages (not generated by generate_pages.js)
const files = [
  'index.html', 'listings.html', 'cities.html', 'profile.html',
  'map.html', 'deals.html', 'search.html', 'best-places.html',
  'add-listing.html', 'login.html', 'admin.html',
  'city-bangkok.html', 'city-pattaya.html', 'city-chiangmai.html',
  'city-phuket.html', 'city-huahin.html', 'city-bali.html', 'city-hcmc.html',
  '_listing-template.html'
];

let updated = 0;
files.forEach(f => {
  const fp = path.join(ROOT, f);
  if (!fs.existsSync(fp)) return;
  let html = fs.readFileSync(fp, 'utf-8');
  const orig = html;

  // 1. Remove Home nav tab (desktop)
  html = html.replace(/\s*<a href="index\.html" class="nav-tab">🏠 Home<\/a>\n?/g, '\n');

  // 2. Remove Browse nav tab (desktop)
  html = html.replace(/\s*<a href="listings\.html" class="nav-tab">🔍 Browse<\/a>\n?/g, '\n');

  // 3. Update active-state: listing pages no longer highlight Browse
  html = html.replace(
    /\/\/ Listing pages → highlight Browse tab\s*\n\s*if \(page\.indexOf\('listing-'\) === 0 && href === 'listings\.html'\)/g,
    "// Listing pages → highlight Search tab\n    if (page.indexOf('listing-') === 0 && href === 'search.html')"
  );

  // 4. Remove Browse from bottom nav (various patterns)
  // Pattern: <a href="listings.html" class="bi...">...</a>
  html = html.replace(/\s*<a href="listings\.html" class="bi[^"]*">[\s\S]*?<\/a>/g, '');
  // Pattern: <a href="listings.html" class="bnav-item...">...</a>
  html = html.replace(/\s*<a href="listings\.html" class="bnav-item[^"]*">[\s\S]*?<\/a>/g, '');

  // 5. Remove Browse from footer links
  html = html.replace(/\s*<a href="listings\.html">Browse<\/a>\n?/g, '\n');

  if (html !== orig) {
    fs.writeFileSync(fp, html);
    updated++;
    console.log(`  Updated: ${f}`);
  } else {
    console.log(`  No changes: ${f}`);
  }
});

console.log(`\nDone. Updated ${updated} files.`);
